# PostgreSQL for all environments (via Docker Compose)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>

development:
  primary:
    <<: *default
    database: tsumugy_development
  cable:
    <<: *default
    database: tsumugy_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: tsumugy_test
  cable:
    <<: *default
    database: tsumugy_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: tsumugy_production
    username: <%= ENV.fetch("DATABASE_USERNAME") { "tsumugy" } %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tsumugy_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tsumugy_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tsumugy_production_cable
    migrations_paths: db/cable_migrate
