# PostgreSQL for all environments (via Docker Compose)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: tsumugy_development

test:
  <<: *default
  database: tsumugy_test

production:
  primary: &primary_production
    <<: *default
    database: tsumugy_production
    username: <%= ENV.fetch("DB_USERNAME") { "tsumugy" } %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tsumugy_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tsumugy_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tsumugy_production_cable
    migrations_paths: db/cable_migrate
